workflows:
  ios-build-workflow:
    name: iOS Build Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - app_store_credentials
      vars:
        XCODE_PROJECT: "Unity-iPhone.xcodeproj"
        XCODE_SCHEME: "Unity-iPhone"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
    scripts:
      - name: Git LFS files checkout
        script: | 
          git lfs pull
      - name: Fix Unity Script Permissions
        script: |
          chmod +x process_symbols.sh || true
      - name: Initialize keychain and code signing
        script: |
          keychain initialize
          xcode-project use-profiles
      - name: Increment build number
        script: |
          agvtool new-version -all $BUILD_NUMBER
      - name: Build ipa for App Store
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --archive-xcargs "PRODUCT_BUNDLE_IDENTIFIER=com.solmaz.blokgame CODE_SIGN_STYLE=Automatic"
    artifacts:
      - build/ios/ipa/*.ipa
